server:
  port: 8081

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://integrator-4271402.okta.com/oauth2/default

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
