server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/amazon_microservices
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    function:
      definition: paymentFailedConsumer;paymentSuccessConsumer

    stream:
      bindings:
        orderCreated-out-0:
          destination: order-created

        paymentFailedConsumer-in-0:
          destination: payment-failed
          group: order-payment-failed-group

        paymentSuccessConsumer-in-0:
          destination: payment-success
          group: order-payment-success-group

      kafka:
        binder:
          brokers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:
  circuitbreaker:
    instances:
      productService:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
