spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/amazon_microservices
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    function:
      definition: orderCreatedConsumer

    stream:
      kafka:
        binder:
          brokers: localhost:9092

      bindings:

        orderCreatedConsumer-in-0:
          destination: order-created
          group: payment-service-group

        paymentSuccess-out-0:
          destination: payment-success

        paymentFailed-out-0:
          destination: payment-failed

server:
  port: 8087
