spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/paymentdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092

server:
  port: 8087
